### ISSUE TITLE
Error installing Windows software

### ISSUE THREAD

**Issue by Arakistech** [Green-bms/GreenDetect#1]
When running setup.exe, I get this error: "El archivo GreenDetect.exe.config tiene un hash calculado distinto al especificado en el manifiesto."

**Comment by Green-bms** [comment]
Hi,

   try to download Windows software from this link: https://hackaday.io/project/186064-green-detect

   go to files section and click on:  04 Win application.zip

   Bye.

   Sergio

   Da "Arakistech" ***@***.***
   A "Green-bms/GreenDetect" ***@***.***
   Cc "Subscribed" ***@***.***
   Data Thu, 22 Dec 2022 06:51:12 -0800
   Oggetto [Green-bms/GreenDetect] Error installing Windows software (Issue #1)

   When running setup.exe, I get this error: "El archivo GreenDetect.exe.config tiene un hash calculado distinto al especificado en el manifiesto."

**Comment by Arakistech** [comment]
With the new download, I don´t get the error, but the program does not start.

**Comment by Green-bms** [comment]
strange...

   try to check on windows app management if GreenDetect app is already present

   If yes, uninstall it and install again.

   If not try to restart the computer

   Da "Arakistech" ***@***.***
   A "Green-bms/GreenDetect" ***@***.***
   Cc "Green-bms" ***@***.***,"Comment" ***@***.***
   Data Thu, 22 Dec 2022 07:21:27 -0800
   Oggetto Re: [Green-bms/GreenDetect] Error installing Windows software (Issue #1)

   With the new download, I don´t get the error, but the program does not start.

**Comment by ahsanfi** [comment]
Hi, I also have error when installing the program. @Green-bms 

![image](https://user-images.githubusercontent.com/106282732/217772792-8b99da33-182d-4d37-9f35-8daca91d93a4.png)

**And this is the error detail:**
> PLATFORM VERSION INFO
> 	Windows 			: 10.0.22623.0 (Win32NT)
> 	Common Language Runtime 	: 4.0.30319.42000
> 	System.Deployment.dll 		: 4.8.9032.0 built by: NET481REL1
> 	clr.dll 			: 4.8.9105.0 built by: NET481REL1LAST_C
> 	dfdll.dll 			: 4.8.9032.0 built by: NET481REL1
> 	dfshim.dll 			: 10.0.22621.30000 (WinBuild.160101.0800)
> 
> SOURCES
> 	Deployment url			: file:///E:/OneDrive/OneDrive%20-%20Universitas%20Diponegoro/KEGIATAN%20LAIN/LOMBA/PKM%202023/SMART%20FOREST%20PROTECTOR/PROTOTYPE/GreenDetect-master/GreenDetect-master/04%20Win%20application/GreenDetect.application
> 	Application url			: file:///E:/OneDrive/OneDrive%20-%20Universitas%20Diponegoro/KEGIATAN%20LAIN/LOMBA/PKM%202023/SMART%20FOREST%20PROTECTOR/PROTOTYPE/GreenDetect-master/GreenDetect-master/04%20Win%20application/Application%20Files/GreenDetect_1_0_0_44/GreenDetect.exe.manifest
> 
> IDENTITIES
> 	Deployment Identity		: GreenDetect.application, Version=1.0.0.44, Culture=neutral, PublicKeyToken=9ba089cdd6a5cde1, processorArchitecture=msil
> 	Application Identity		: GreenDetect.exe, Version=1.0.0.44, Culture=neutral, PublicKeyToken=9ba089cdd6a5cde1, processorArchitecture=msil, type=win32
> 
> APPLICATION SUMMARY
> 	* Installable application.
> 
> ERROR SUMMARY
> 	Below is a summary of the errors, details of these errors are listed later in the log.
> 	* Activation of E:\OneDrive\OneDrive - Universitas Diponegoro\KEGIATAN LAIN\LOMBA\PKM 2023\SMART FOREST PROTECTOR\PROTOTYPE\GreenDetect-master\GreenDetect-master\04 Win application\GreenDetect.application resulted in exception. Following failure messages were detected:
> 		+ File, GreenDetect.exe.config, has a different computed hash than specified in manifest.
> 
> COMPONENT STORE TRANSACTION FAILURE SUMMARY
> 	No transaction error was detected.
> 
> WARNINGS
> 	There were no warnings during this operation.
> 
> OPERATION PROGRESS STATUS
> 	* [09/02/2023 16:28:43] : Activation of E:\OneDrive\OneDrive - Universitas Diponegoro\KEGIATAN LAIN\LOMBA\PKM 2023\SMART FOREST PROTECTOR\PROTOTYPE\GreenDetect-master\GreenDetect-master\04 Win application\GreenDetect.application has started.
> 	* [09/02/2023 16:28:43] : Processing of deployment manifest has successfully completed.
> 	* [09/02/2023 16:28:43] : Installation of the application has started.
> 	* [09/02/2023 16:28:43] : Processing of application manifest has successfully completed.
> 	* [09/02/2023 16:28:45] : Found compatible runtime version 4.0.30319.
> 	* [09/02/2023 16:28:45] : Request of trust and detection of platform is complete.
> 
> ERROR DETAILS
> 	Following errors were detected during this operation.
> 	* [09/02/2023 16:28:46] System.Deployment.Application.InvalidDeploymentException (HashValidation)
> 		- File, GreenDetect.exe.config, has a different computed hash than specified in manifest.
> 		- Source: System.Deployment
> 		- Stack trace:
> 			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, Hash hash)
> 			at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, HashCollection hashCollection)
> 			at System.Deployment.Application.ComponentVerifier.VerifyComponents()
> 			at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
> 			at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
> 			at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
> 			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
> 			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
> --- End of stack trace from previous location where exception was thrown ---
> 			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> 			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
> 			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
> 
> COMPONENT STORE TRANSACTION DETAILS
> 	No transaction information is available.
> 
>

**Comment by Green-bms** [comment]
Hi,

   first of all, check on windows app management if GreenDetect app is already present: If yes, uninstall it.

   After that, try to download Windows software from this link: https://hackaday.io/project/186064-green-detect

   go to files section and click on: 04 Win application.zip Bye. Sergio

   Da "Muhammad Ahsan Fillah Abadi" ***@***.***
   A "Green-bms/GreenDetect" ***@***.***
   Cc "Green-bms" ***@***.***,"Mention" ***@***.***
   Data Thu, 09 Feb 2023 01:31:27 -0800
   Oggetto Re: [Green-bms/GreenDetect] Error installing Windows software (Issue #1)

   Hi, I also have error when installing the program. @Green-bms

   And this is the error detail:

     PLATFORM VERSION INFO
     Windows : 10.0.22623.0 (Win32NT)
     Common Language Runtime : 4.0.30319.42000
     System.Deployment.dll : 4.8.9032.0 built by: NET481REL1
     clr.dll : 4.8.9105.0 built by: NET481REL1LAST_C
     dfdll.dll : 4.8.9032.0 built by: NET481REL1
     dfshim.dll : 10.0.22621.30000 (WinBuild.160101.0800)

     SOURCES
     Deployment url : file:///E:/OneDrive/OneDrive%20-%20Universitas%20Diponegoro/KEGIATAN%20LAIN/LOMBA/PKM%202023/SMART%20FOREST%20PROTECTOR/PROTOTYPE/GreenDetect-master/GreenDetect-master/04%20Win%20application/GreenDetect.application
     Application url : file:///E:/OneDrive/OneDrive%20-%20Universitas%20Diponegoro/KEGIATAN%20LAIN/LOMBA/PKM%202023/SMART%20FOREST%20PROTECTOR/PROTOTYPE/GreenDetect-master/GreenDetect-master/04%20Win%20application/Application%20Files/GreenDetect_1_0_0_44/GreenDetect.exe.manifest

     IDENTITIES
     Deployment Identity : GreenDetect.application, Version=1.0.0.44, Culture=neutral, PublicKeyToken=9ba089cdd6a5cde1, processorArchitecture=msil
     Application Identity : GreenDetect.exe, Version=1.0.0.44, Culture=neutral, PublicKeyToken=9ba089cdd6a5cde1, processorArchitecture=msil, type=win32

     APPLICATION SUMMARY
     * Installable application.

     ERROR SUMMARY
     Below is a summary of the errors, details of these errors are listed later in the log.
     * Activation of E:\OneDrive\OneDrive - Universitas Diponegoro\KEGIATAN LAIN\LOMBA\PKM 2023\SMART FOREST PROTECTOR\PROTOTYPE\GreenDetect-master\GreenDetect-master\04 Win application\GreenDetect.application resulted in exception. Following failure messages were detected:
          + File, GreenDetect.exe.config, has a different computed hash than specified in manifest.

     COMPONENT STORE TRANSACTION FAILURE SUMMARY
     No transaction error was detected.

     WARNINGS
     There were no warnings during this operation.

     OPERATION PROGRESS STATUS
     * [09/02/2023 16:28:43] : Activation of E:\OneDrive\OneDrive - Universitas Diponegoro\KEGIATAN LAIN\LOMBA\PKM 2023\SMART FOREST PROTECTOR\PROTOTYPE\GreenDetect-master\GreenDetect-master\04 Win application\GreenDetect.application has started.
     * [09/02/2023 16:28:43] : Processing of deployment manifest has successfully completed.
     * [09/02/2023 16:28:43] : Installation of the application has started.
     * [09/02/2023 16:28:43] : Processing of application manifest has successfully completed.
     * [09/02/2023 16:28:45] : Found compatible runtime version 4.0.30319.
     * [09/02/2023 16:28:45] : Request of trust and detection of platform is complete.

     ERROR DETAILS
     Following errors were detected during this operation.
     * [09/02/2023 16:28:46] System.Deployment.Application.InvalidDeploymentException (HashValidation)
          + File, GreenDetect.exe.config, has a different computed hash than specified in manifest.
          + Source: System.Deployment
          + Stack trace:
            at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, Hash hash)
            at System.Deployment.Application.ComponentVerifier.VerifyFileHash(String filePath, HashCollection hashCollection)
            at System.Deployment.Application.ComponentVerifier.VerifyComponents()
            at System.Deployment.Application.DownloadManager.DownloadDependencies(SubscriptionState subState, AssemblyManifest deployManifest, AssemblyManifest appManifest, Uri sourceUriBase, String targetDirectory, String group, IDownloadNotification notification, DownloadOptions options)
            at System.Deployment.Application.ApplicationActivator.DownloadApplication(SubscriptionState subState, ActivationDescription actDesc, Int64 transactionId, TempDirectory& downloadTemp)
            at System.Deployment.Application.ApplicationActivator.InstallApplication(SubscriptionState& subState, ActivationDescription actDesc)
            at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
            at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
            --- End of stack trace from previous location where exception was thrown ---
            at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
            at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
            at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)

     COMPONENT STORE TRANSACTION DETAILS
     No transaction information is available.

**Comment by ahsanfi** [comment]
Thank you so much for your answer.
I have another question. Can I switch the Supercapacitor with 18650 Lithium Battery?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Green-bms** [comment]
No, you can't replace with lithium batteries: different voltage, different charging circuit.
You can replace Supercap with 2s Nimh batteries: this is an option of the project.
![modulo nimh - Copia](https://user-images.githubusercontent.com/89488863/217886786-ef99bb1e-a846-4762-9415-c8bf394aa5a9.png)

**Comment by ahsanfi** [comment]
OK, thank you. Have you any preferences what Nimh batteries can I use?


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Green-bms** [comment]
I suggest to use 2 x batteries AA 2800 mA Nimh, with a dedicated holder.
This is an example of batteries: https://www.amazon.com/POWEROWL-Rechargeable-Batteries-Capacity-Discharge/dp/B07M7JGTP7/ref=psdc_15745581_t5_B07MQ8YRF3
This is an example of holder: https://www.amazon.com/WAYLLSHINE-2Pcs-Battery-Holder-Leads/dp/B09V7Z4MT7/ref=sr_1_1?crid=2VEW8ZXYR25XN&keywords=aa+battery+holder&qid=1675964432&sprefix=aa+battery+holder%2Caps%2C175&sr=8-1

**Comment by ahsanfi** [comment]
Thank you so much ❤️

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
